#!/bin/bash

app=dockercontainer
name=$(sudo yunohost app setting $app name)
repository=$(sudo yunohost app setting $app repository)
datacontainer=$(sudo yunohost app setting $app datacontainer)

# The parameter $1 is the backup directory location which will be compressed afterward
	backup_dir=$1/apps/container-$name
	mkdir -p $backup_dir

# Backup container's volumes
	if [ "$datacontainer" = "Yes" ];
	then
		echo 'Backing up with data container'
		sudo docker stop $name
		sudo docker stop $name-data
		sudo docker run --rm --volumes-from $name-data -v $backup_dir:/backup $repository tar cvf /backup/container-$name.tar
	else
		echo 'Backing up without data container'
		sudo docker stop $name
		docker run --rm --volumes-from $name -v $backup_dir:/backup $repository tar cvf /backup/container-$name.tar
	fi

# Copy the systemd service
	sudo cp -a /etc/systemd/system/container-$name.service $backup_dir/container-$name.service

# Copy YunoHost parameters
	sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost