#!/bin/bash

set -e

# Retrieve arguments
domain=$1
name=$2
repository=$3
restart=$4
command=$5

# Check ports availability
#sudo yunohost app checkport 9000
#if [[ ! $? -eq 0 ]]; then
#  exit 1
#fi

sudo yunohost app setting dockercontainer name -v $name

# Install Docker if it is not installed yet
if [ -f /usr/bin/docker ]; then
	echo "Docker is already installed"
else
	echo "Docker will now be installed"
	sudo apt-get install curl -y -qq
	sudo curl -sSL https://get.docker.com/ | sh
	sudo yunohost service add docker
	sudo service docker start 
	sudo usermod -aG docker admin
	newgrp docker
fi
sudo service docker restart

# Create Docker container
if [ "$restart" = "Yes" ];
then
	command+=" --restart always"
fi

sudo docker run -d $command --name=$name $repository

# Manage container as daemon
#sed -i "s@CONTAINERNAME$name@g" ../conf/init.d
#sudo cp ../conf/init.d /etc/init.d/container-$name
#sudo chmod 0755 /etc/init.d/container-$name
#sudo yunohost service add container-$name

sudo service nginx reload
sudo yunohost app ssowatconf