#!/bin/bash

# Retrieve arguments
name=${1,,}
repository=$2
restart=$3
datacontainer=$4
volume=$5
command=$6

# Check container's ports availability - TBD
#sudo yunohost app checkport 9000
#if [[ ! $? -eq 0 ]]; then
#  exit 1
#fi

# Install Docker if it is not installed yet
if [ -f /usr/bin/docker ]; then
	echo "Docker is already installed"
else
	echo "Docker will now be installed"
	sudo apt-get install curl -y -qq
	sudo curl -sSL https://get.docker.com/ | sh
	sudo yunohost service add docker
	sudo update-rc.d docker defaults
	sudo service docker start 
	sudo usermod -aG docker admin
	newgrp docker
fi
sudo service docker restart

# Create Docker container
sudo yunohost app setting dockercontainer name -v $name
sudo yunohost app setting dockercontainer repository -v $repository
sudo yunohost app setting dockercontainer datacontainer -v $datacontainer
sudo yunohost app setting dockercontainer volume -v $volume

if [ "$volume" = "Yes" ];
then
	sudo mkdir -p /home/yunohost.docker/container-$name
fi

if [ "$restart" = "Yes" ];
then
	command+=" --restart always"
fi

if [ "$datacontainer" = "Yes" ];
then
	sudo docker create --name=$name-data $repository /bin/true
	command+=" --volumes-from $name-data"
fi

sudo yunohost app setting dockercontainer command -v $command
sudo docker run -d $command --name=$name $repository

# Manage container as daemon with systemd - only compatible with Debian Jessie & YNH 2.2
sudo sed -i "s@CONTAINERNAME@$name@g" ../conf/systemd.service
sudo cp ../conf/systemd.service /etc/systemd/system/container-$name.service
sudo chmod 777 /etc/systemd/system/container-$name.service
sudo systemctl enable /etc/systemd/system/container-$name.service
sudo systemctl daemon-reload
sudo yunohost service add container-$name