#!/bin/bash

# Remove Docker container and systemd service but keep the pulled image and Docker
name=$(sudo yunohost app setting dockercontainer name)
sudo yunohost service remove container-$name
sudo rm /etc/systemd/system/multi-user.target.wants/container-$name.service
sudo docker stop $name
sudo docker rm $name

# Remove NGINX conf
redirect=$(sudo yunohost app setting dockercontainer redirect)
if [ "$redirect" = "Yes" ];
then
	domain=$(sudo yunohost app setting dockercontainer domain)
	sudo rm /etc/nginx/conf.d/$domain.d/dockercontainer.conf
fi

# Remove home folder
home=$(sudo yunohost app setting dockercontainer home)
if [ "$home" = "Yes" ];
then
	sudo rm -rf /home/yunohost.docker/container-$name
fi

# Reload
sudo service nginx reload
sudo yunohost app ssowatconf 