#!/bin/bash

domain=$(sudo yunohost app setting dockercontainer domain)
name=$(sudo yunohost app setting dockercontainer name)

sudo yunohost service remove container-$name
sudo rm /etc/init.d/container-$name

sudo docker stop $name
sudo docker rm $name

sudo service nginx reload
sudo yunohost app ssowatconf 